# Generated by Django 4.1.6 on 2023-02-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("phone", models.IntegerField(verbose_name="Contact Number")),
                (
                    "insta",
                    models.CharField(max_length=200, verbose_name="Instagram ID"),
                ),
                ("score", models.IntegerField(default=0)),
            ],
        ),
    ]
